---
# tasks file for csr
- name: install openssl and python
  package:
    name: openssl, python
    state: latest

- name: ensure pip
  shell: which pip
  # ignore an error for next block
  register: result
  failed_when: result.rc < 0

- block:
  - name: download get-pip.py
    get_url:
      dest: ~/get-pip.py
      url: https://bootstrap.pypa.io/get-pip.py
  - name: install pip
    shell: python ~/get-pip.py
  when: result.rc > 0

- name: install pyOpenSSL
  pip:
    name: pyOpenSSL
    state: present


- name: ensure store fir exist
  file:
    mode: 0664
    path: "{{ remote_store_dir }}"
    state: directory

- name: ensure created target hosts private key
  openssl_privatekey:
    path: "{{ remote_store_dir }}/{{ inventory_hostname }}_key.pem"
    state: present

- name: ensure created csr
  openssl_csr:
    commonName: "{{ common_name }}"
    countryName: "{{ country_name }}"
    emailAddress: "{{ email }}"
    localityName: "{{ locality_name }}"
    organizationName: "{{ organization_name }}"
    organizationalUnitName: "{{ organization_unit_name }}"
    stateOrProvinceName: "{{ state_or_province_name }}"
    path: "{{ remote_store_dir }}/{{ inventory_hostname }}.csr"
    privatekey_path: "{{ remote_store_dir }}/{{ inventory_hostname }}_key.pem"
    state: present


- name: ensure fetch csr file
  fetch:
    src: "{{ remote_store_dir }}/{{ inventory_hostname }}.csr"
    dest: "{{ local_store_dir }}/{{ inventory_hostname }}.csr"
    fail_on_missing: yes
    flat: yes
