---
# tasks file for ansible
- name: install openssl and python
  package:
    name: openssl, python
    state: latest

- name: ensure pip
  shell: which pip
  # ignore an error for next block
  register: result
  failed_when: result.rc < 0

- block:
  - name: download get-pip.py
    get_url:
      dest: ~/get-pip.py
      url: https://bootstrap.pypa.io/get-pip.py
  - name: install pip
    shell: python ~/get-pip.py
  when: result.rc > 0

- name: install pyOpenSSL
  pip:
    name: pyOpenSSL
    state: present

- name: create ca private key
  openssl_privatekey:
    path: "{{ abs_ca_key }}"
    state: present

- name: create csr
  openssl_csr:
    commonName: "{{ ca_common_name }}"
    countryName: "{{ ca_country_name }}"
    emailAddress: "{{ ca_email }}"
    localityName: "{{ ca_locality_name }}"
    organizationName: "{{ ca_organization_name }}"
    organizationalUnitName: "{{ ca_organization_unit_name }}"
    privatekey_path: "{{ abs_ca_key }}"
    stateOrProvinceName: "{{ ca_state_or_province_name }}"
    path: "{{ abs_ca_cert_csr }}"
    state: present


- name: create self signed certificate
  openssl_certificate:
    csr_path: "{{ abs_ca_cert_csr }}"
    privatekey_path: "{{ abs_ca_key }}"
    provider: selfsigned
    valid_in: 315360000
    path: "{{ abs_ca_cert_pem }}"
    state: present

- name: convert CA certificate to DER
  shell: "openssl x509 -inform PEM -outform DER -in {{ abs_ca_cert_pem }} -out {{ abs_ca_cert_der }}"
  args:
    creates: "{{ abs_ca_cert_der }}"

- name: create index file
  file:
    path: "{{ ca_dir }}/index.txt"
    state: touch

- name: create serial file
  shell: "echo '01' > {{ ca_dir }}/serial"
  args:
    creates: "{{ ca_dir }}/serial"

- name: download CA certificate
  fetch:
    src: "{{ abs_ca_cert_der }}"
    dest: "{{ local_store_dir }}/{{ ca_cert_der }}"
    fail_on_missing: yes
    flat: yes


# signed csrs
- name: create csr store
  file:
    mode: 0664
    path: "{{ ca_csr_store_dir }}"
    state: directory

- name: Check if remote csrs exists
  stat:
    path: "{{ ca_csr_store_dir }}/{{ item }}.csr"
  with_items: "{{ groups['csr'] }}"
  register: existence
  tags: checkfiles

- name: copy local csrs to remote ca
  copy:
    src: "{{ local_store_dir }}/{{ item.item }}.csr"
    dest: "{{ ca_csr_store_dir }}/{{ item.item }}.csr"
  when: item.stat.exists == False
  with_items: "{{ existence.results }}"

- name: create certificates signed by ca
  openssl_certificate:
    csr_path: "{{ ca_csr_store_dir }}/{{ item.item }}.csr"
    privatekey_path: "{{ abs_ca_key }}"
    provider: selfsigned
    valid_in: 315360000
    path: "{{ ca_csr_store_dir }}/{{ item.item }}.cert.pem"
    state: present
  when: item.stat.exists
  with_items: "{{ existence.results }}"

- name: download certificates to local
  fetch:
    src: "{{ ca_csr_store_dir }}/{{ item.item }}.cert.pem"
    dest: "{{ local_store_dir }}/{{ item.item }}.cert.pem"
    fail_on_missing: yes
    flat: yes
  when: item.stat.exists
  with_items: "{{ existence.results }}"