---
# defaults file for ca
ca_dir: /etc/pki/CA
private_dir: private
certs_dir: certs
ca_key: ca_key.pem
ca_cert_csr: ca_cert.csr
ca_cert_pem: ca_cert.pem

abs_ca_key: "{{ ca_dir }}/{{ private_dir }}/{{ ca_key }}"
abs_ca_cert_csr: "{{ ca_dir }}/{{ certs_dir }}/{{ ca_cert_csr }}"
abs_ca_cert_pem: "{{ ca_dir }}/{{ certs_dir }}/{{ ca_cert_pem }}"

key_size: 2048
